In [1]:
import numpy as np

1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
arr = np.zeros(10,)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.

In [3]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
arr1 = np.array([1,2,0,0,4,0])
np.nonzero(arr1)

(array([0, 1, 4], dtype=int64),)

5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
arr2 = np.random.random(size =(10,10))
print(arr2)
print(f"Max. value is {arr2.max()}")
print(f"Min. value is {arr2.min()}")

[[0.93175969 0.84235225 0.97785135 0.48330816 0.96615771 0.81515657
  0.13820118 0.10305807 0.02174964 0.89314921]
 [0.93662184 0.85670658 0.93796328 0.73253369 0.85938614 0.83132808
  0.05919702 0.93153155 0.13525939 0.17199532]
 [0.49381659 0.19696862 0.52920317 0.11265943 0.76038479 0.3065503
  0.0833951  0.3773096  0.38540942 0.2017838 ]
 [0.40337369 0.57380263 0.62560597 0.41773387 0.74382252 0.27547332
  0.63312228 0.75946562 0.98428196 0.70169802]
 [0.20545151 0.7557947  0.28081403 0.48103155 0.99815941 0.76067845
  0.69617686 0.90368268 0.09917148 0.67986773]
 [0.50373332 0.92493409 0.42513011 0.94377556 0.19169337 0.94083282
  0.91531783 0.4970729  0.36458392 0.22225502]
 [0.2243923  0.04169587 0.01925036 0.12054966 0.70225048 0.92251396
  0.69228994 0.25150997 0.17369521 0.06833428]
 [0.30208137 0.49392773 0.74202876 0.63791674 0.93755116 0.27820455
  0.86021955 0.40996195 0.88760166 0.83106068]
 [0.73488307 0.7451003  0.64447824 0.60208454 0.59595634 0.44560094
  0.18197637 

6. Create a random vector of size 30 and find the mean value.

In [7]:
np.random.random(size = 30).mean()

0.5050738842642563